# Generated by Django 3.1.2 on 2021-05-02 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=100)),
                ('college_address', models.CharField(blank=True, max_length=100, null=True)),
                ('college_city', models.CharField(max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'college',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('sno', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('rating', models.CharField(blank=True, choices=[('Bad', 'Bad'), ('Average', 'Average'), ('Good', 'Good'), ('Excellent', 'Excellent')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default=None, max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=10, null=True)),
                ('tenth_per', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('twelth_per', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('tenth_brd', models.CharField(choices=[('SB', 'SB'), ('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('IB', 'IB')], max_length=5, null=True)),
                ('twelth_brd', models.CharField(choices=[('SB', 'SB'), ('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('IB', 'IB')], max_length=5, null=True)),
                ('twelth_stream', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('result', models.IntegerField(default=0)),
                ('date_appeared', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('std', models.CharField(choices=[('10th', '10th'), ('12th', '12th')], default=None, max_length=4)),
                ('sub_name', models.CharField(blank=True, max_length=20, null=True)),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='api.student')),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('stream_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stream_name', models.CharField(max_length=20)),
                ('main_stream', models.CharField(max_length=20)),
                ('cut_off', models.DecimalField(decimal_places=2, max_digits=4)),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='api.college')),
            ],
            options={
                'db_table': 'stream',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('question', models.CharField(max_length=250)),
                ('option_A', models.CharField(blank=True, max_length=250, null=True)),
                ('option_B', models.CharField(blank=True, max_length=250, null=True)),
                ('option_C', models.CharField(blank=True, max_length=250, null=True)),
                ('option_D', models.CharField(blank=True, max_length=250, null=True)),
                ('answer', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, null=True)),
                ('explanation', models.CharField(blank=True, max_length=250, null=True)),
                ('given_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stream_name', models.CharField(blank=True, max_length=20, null=True)),
                ('date_applied', models.DateField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False, null=True)),
                ('accepted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_by', to='api.college')),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_to', to='api.college')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'db_table': 'application',
            },
        ),
    ]
